export const PLACE_CATEGORIES = [
  'Restaurant',
  'Hospital',
  'Hotel',
  'Parking',
  'Shop',
  'Grocery Store',
  'School',
  'Temple',
  'Bank',
  'Post Office',
  'Bus Stop',
  'Police Station',
  'Petrol Pump',
  'Tourist Place',
  'Transit',
  'Museum',
  'Pharmacy',
  'ATM',
  'Cinema',
  'Gym',
  'Salon',
  'Other',
]

/** Natural-language terms → canonical category label. */
export const CATEGORY_ALIASES = {
  restaurant: 'Restaurant',
  restaurants: 'Restaurant',
  food: 'Restaurant',
  cafe: 'Restaurant',
  hotel: 'Hotel',
  hotels: 'Hotel',
  lodging: 'Hotel',
  hospital: 'Hospital',
  hospitals: 'Hospital',
  clinic: 'Hospital',
  pharmacy: 'Pharmacy',
  pharmacies: 'Pharmacy',
  chemist: 'Pharmacy',
  atm: 'ATM',
  atms: 'ATM',
  bank: 'Bank',
  banks: 'Bank',
  temple: 'Temple',
  temples: 'Temple',
  church: 'Temple',
  mosque: 'Temple',
  school: 'School',
  schools: 'School',
  museum: 'Museum',
  museums: 'Museum',
  shop: 'Shop',
  shops: 'Shop',
  store: 'Shop',
  grocery: 'Grocery Store',
  supermarket: 'Grocery Store',
  petrol: 'Petrol Pump',
  'petrol pump': 'Petrol Pump',
  gas: 'Petrol Pump',
  'gas station': 'Petrol Pump',
  parking: 'Parking',
  bus: 'Bus Stop',
  'bus stop': 'Bus Stop',
  police: 'Police Station',
  post: 'Post Office',
  'post office': 'Post Office',
  gym: 'Gym',
  cinema: 'Cinema',
  theater: 'Cinema',
  salon: 'Salon',
  tourist: 'Tourist Place',
  transit: 'Transit',
}
