export const PLACE_CATEGORIES = [
  'Restaurant',
  'Hospital',
  'Hotel',
  'Parking',
  'Shop',
  'Grocery Store',
  'School',
  'Temple',
  'Bank',
  'Post Office',
  'Bus Stop',
  'Police Station',
  'Petrol Pump',
  'Tourist Place',
  'Transit',
  'Museum',
  'Pharmacy',
  'ATM',
  'Cinema',
  'Gym',
  'Salon',
  'Festival',
  'Other',
]

/** Natural-language terms → canonical category label. */
export const CATEGORY_ALIASES = {
  restaurant: 'Restaurant',
  restaurants: 'Restaurant',
  food: 'Restaurant',
  cafe: 'Restaurant',
  hotel: 'Hotel',
  hotels: 'Hotel',
  lodging: 'Hotel',
  hospital: 'Hospital',
  hospitals: 'Hospital',
  clinic: 'Hospital',
  pharmacy: 'Pharmacy',
  pharmacies: 'Pharmacy',
  chemist: 'Pharmacy',
  atm: 'ATM',
  atms: 'ATM',
  bank: 'Bank',
  banks: 'Bank',
  temple: 'Temple',
  temples: 'Temple',
  church: 'Temple',
  mosque: 'Temple',
  school: 'School',
  schools: 'School',
  museum: 'Museum',
  museums: 'Museum',
  shop: 'Shop',
  shops: 'Shop',
  store: 'Shop',
  grocery: 'Grocery Store',
  supermarket: 'Grocery Store',
  'general store': 'Grocery Store',
  petrol: 'Petrol Pump',
  'petrol pump': 'Petrol Pump',
  gas: 'Petrol Pump',
  'gas station': 'Petrol Pump',
  parking: 'Parking',
  bus: 'Bus Stop',
  'bus stop': 'Bus Stop',
  police: 'Police Station',
  post: 'Post Office',
  'post office': 'Post Office',
  gym: 'Gym',
  cinema: 'Cinema',
  theater: 'Cinema',
  salon: 'Salon',
  tourist: 'Tourist Place',
  transit: 'Transit',
}

/** Match places whose name contains these when category field is wrong/missing. */
export const CATEGORY_NAME_KEYWORDS = {
  Hotel: ['hotel', 'lodge', 'resort', 'inn', 'guest', 'homestay', 'lodging', 'stay'],
  Restaurant: ['restaurant', 'dhaba', 'eatery', 'biryani', 'cafe'],
  ATM: ['atm', 'cash point'],
  Pharmacy: ['pharmacy', 'chemist', 'medical store', 'medicals'],
  Hospital: ['hospital', 'hospitals', 'clinic', 'nursing home', 'health centre', 'health center', 'medical college', 'dispensary'],
  Temple: ['temple', 'masjid', 'mosque', 'church', 'juma', 'dargah'],
  Bank: ['bank'],
  'Petrol Pump': ['petrol', 'fuel', 'gas station', 'filling'],
  'Bus Stop': ['bus stop', 'bus stand'],
  'Grocery Store': ['general stores', 'general store', 'grocery store', 'grocery', 'supermarket', 'provision store', 'provisions store', 'kirana', 'provisions', 'departmental store'],
  Shop: ['shop', 'mart'],
}
