import { lazy } from 'react'

/** Heavy Home map features — loaded only when opened / after first paint. */
export const RoutePanel = lazy(() => import('./RoutePanel'))
export const NavigationView = lazy(() => import('./NavigationView'))
export const AskMapsPanel = lazy(() => import('./AskMapsPanel'))
export const AddPlaceModal = lazy(() => import('./AddPlaceModal'))
export const AddPlaceMethodModal = lazy(() => import('./AddPlaceMethodModal'))
export const PlaceDetailPanel = lazy(() => import('./PlaceDetailPanel'))
export const PlaceExtractPanel = lazy(() => import('./PlaceExtractPanel'))
export const DuplicatePlaceModal = lazy(() => import('./DuplicatePlaceModal'))
export const PlaceAddedSuccessModal = lazy(() => import('./PlaceAddedSuccessModal'))
export const PolygonExplorePanel = lazy(() => import('./PolygonExplorePanel'))
export const UpcomingFestivalsPanel = lazy(() => import('./UpcomingFestivalsPanel'))
export const FeedbackModal = lazy(() => import('./FeedbackModal'))
export const OnboardingTour = lazy(() => import('./OnboardingTour'))
export const LiveLocationShareSheet = lazy(() => import('./LiveLocationShareSheet'))
export const LiveLocationViewerBar = lazy(() => import('./LiveLocationViewerBar'))
export const PublicUtilityFinderSheet = lazy(() => import('./PublicUtilityFinderSheet'))
export const OfflineMapsSheet = lazy(() => import('./OfflineMapsSheet'))
export const HazardReportSheet = lazy(() => import('./HazardReportSheet'))
export const MeasureDistancePanel = lazy(() => import('./MeasureDistancePanel'))
export const MapAssistantChatbot = lazy(() => import('./MapAssistantChatbot'))
export const LanguagePickerModal = lazy(() => import('../lib/i18n/LanguagePickerModal'))
